import { StyleSheet } from "react-native";

// Styles partagés des écrans d'authentification (Login / Register / OTP…)
// Champs de saisie grands et lisibles, palette indigo MoneyTrack.
export const COLORS = {
  base: "#161427",
  primary: "#4F46E5",
  primaryDark: "#3F38C9",
  violet: "#8B5CF6",
  link: "#34D399",
  inputBg: "#FFFFFF",
  inputText: "#111827",
  placeholder: "#9CA3AF",
};

const authStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.base },
  bg: { flex: 1, width: "100%", minHeight: "100%" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.base,
    opacity: 0.86,
  },
  content: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  logo: { width: 96, height: 96, borderRadius: 24, marginBottom: 12 },
  title: { fontSize: 30, fontWeight: "800", color: "#fff", marginBottom: 6 },
  subtitle: {
    color: "#C7C5D6",
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 320,
    marginBottom: 22,
  },
  field: { width: "100%", maxWidth: 360, marginBottom: 16 },
  label: { color: "#E5E7EB", fontWeight: "600", fontSize: 14, marginBottom: 8 },
  input: {
    width: "100%",
    height: 56,
    backgroundColor: COLORS.inputBg,
    borderRadius: 14,
    paddingHorizontal: 18,
    fontSize: 16,
    color: COLORS.inputText,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  button: {
    width: "100%",
    maxWidth: 360,
    height: 56,
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  buttonText: { color: "#fff", fontSize: 18, fontWeight: "700" },
  buttonDisabled: { opacity: 0.6 },
  link: { color: COLORS.link, fontWeight: "700" },
  forgot: { color: COLORS.violet, fontWeight: "600", textAlign: "right" },
  footerText: { color: "#E5E7EB", marginTop: 18, fontSize: 14 },

  // ---------- Thème clair (Forgot / OTP / Reset) ----------
  lightSafe: { flex: 1, backgroundColor: "#fff" },
  lightContent: { flexGrow: 1, paddingHorizontal: 22, paddingTop: 12, paddingBottom: 40 },
  backRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 18 },
  backText: { color: "#111827", fontWeight: "700", fontSize: 18 },
  heading: { fontSize: 28, color: COLORS.primary, fontWeight: "800", textAlign: "left" },
  headingSub: { fontSize: 14, color: "#6B7280", fontWeight: "500", marginTop: 6, lineHeight: 20 },
  illustration: { width: "100%", height: 210, marginTop: 18 },
  lightLabel: { color: "#111827", fontWeight: "600", fontSize: 15, marginBottom: 8 },
  lightInput: {
    width: "100%",
    height: 56,
    backgroundColor: "#F3F4F6",
    borderRadius: 14,
    paddingHorizontal: 18,
    fontSize: 16,
    color: "#111827",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  primaryBtn: {
    width: "100%",
    height: 56,
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 26,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  primaryBtnText: { color: "#fff", fontSize: 18, fontWeight: "700" },
});

export default authStyles;
